# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"password": "00_inputs.ipynb",
         "time": "00_inputs.ipynb",
         "date": "00_inputs.ipynb",
         "number": "00_inputs.ipynb",
         "PandasTable": "01_outputs.ipynb"}

modules = ["inputs.py",
           "outputs.py"]

doc_url = "https://radinplaid.github.io/vvapp"

git_url = "https://github.com/radinplaid/vvapp/tree/master/"

def custom_doc_links(name): return None
