# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"switch": "00_inputs.ipynb",
         "checkbox": "00_inputs.ipynb",
         "text": "00_inputs.ipynb",
         "password": "00_inputs.ipynb",
         "time_input": "00_inputs.ipynb",
         "date": "00_inputs.ipynb",
         "date_range": "00_inputs.ipynb",
         "number": "00_inputs.ipynb",
         "range_slider": "00_inputs.ipynb",
         "slider": "00_inputs.ipynb",
         "radio_buttons": "00_inputs.ipynb",
         "select": "00_inputs.ipynb",
         "select_or_create": "00_inputs.ipynb",
         "button": "00_inputs.ipynb",
         "color_picker": "00_inputs.ipynb",
         "PandasTable": "01_outputs.ipynb",
         "markdown": "01_outputs.ipynb",
         "info_snackbar": "01_outputs.ipynb",
         "dialog_button": "01_outputs.ipynb",
         "container": "01_outputs.ipynb",
         "row": "01_outputs.ipynb",
         "column": "01_outputs.ipynb"}

modules = ["inputs.py",
           "outputs.py"]

doc_url = "https://radinplaid.github.io/vvapp/"

git_url = "https://github.com/radinplaid/vvapp/tree/master/"

def custom_doc_links(name): return None
